language: go

go:
  - "1.10"
env:
  - LIBWEBP_VERSION="0.4.1"
  - LIBWEBP_VERSION="0.4.2"
  - LIBWEBP_VERSION="0.4.3"
  - LIBWEBP_VERSION="0.5.0"
  - LIBWEBP_VERSION="0.5.1"

cache:
  directories:
    - $HOME/cache
sudo: false

before_install:
  - LIBWEBP_PREFIX=$HOME/cache/libwebp-${LIBWEBP_VERSION} make libwebp
  - cd $HOME/gopath/src/github.com/yaminoma/go-libwebp
  - export CGO_CFLAGS="-I $HOME/cache/libwebp-${LIBWEBP_VERSION}/include"
  - export CGO_LDFLAGS="-L $HOME/cache/libwebp-${LIBWEBP_VERSION}/lib"
  - export LD_LIBRARY_PATH=$HOME/cache/libwebp-${LIBWEBP_VERSION}/lib:$LD_LIBRARY_PATH
